/**
 * Backend Setup Helper Script
 * Automatically generates .env file with secure defaults
 * Run with: node backend/setup.js
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

console.log('🚀 CodeSpire Backend Setup\n');

// Generate secure JWT secret
const jwtSecret = crypto.randomBytes(64).toString('hex');

// Default configuration
const envConfig = `# ==========================================
# CodeSpire Backend Environment Variables
# ==========================================
# Auto-generated by setup.js on ${new Date().toLocaleString()}

# ==========================================
# Server Configuration
# ==========================================
NODE_ENV=development
PORT=5000
# Maximum HTTP request header size in bytes (default 64 KB, 4x Node default 16 KB)
MAX_HEADER_SIZE=65536

# ==========================================
# MongoDB Configuration
# ==========================================
# Local MongoDB connection string
MONGO_URI=mongodb://localhost:27017/codespire

# For MongoDB Atlas (cloud), replace with:
# MONGO_URI=mongodb+srv://<username>:<password>@cluster.mongodb.net/codespire?retryWrites=true&w=majority

# ==========================================
# JWT Configuration
# ==========================================
# Auto-generated secure JWT secret
JWT_SECRET=${jwtSecret}

# ==========================================
# CORS Configuration
# ==========================================
# Frontend URL for CORS (React app URL)
CLIENT_URL=http://localhost:3000
`;

// Path to .env file
const envPath = path.join(__dirname, '..', '.env');

// Check if .env already exists
if (fs.existsSync(envPath)) {
  console.log('✅ .env file already exists!');
  console.log('📁 Location:', envPath);
  console.log('\n💡 Your environment is already configured.');
  console.log('   To regenerate, delete .env and run this script again.');
  console.log('   Or manually edit .env to customize settings.\n');
  displaySuccess();
  process.exit(0);
} else {
  // Create new .env file
  try {
    fs.writeFileSync(envPath, envConfig);
    console.log('✅ Created .env file successfully!');
    console.log('📁 Location:', envPath);
    console.log('🔑 Generated secure JWT secret');
    displaySuccess();
    process.exit(0);
  } catch (error) {
    console.error('❌ Error creating .env file:', error.message);
    process.exit(1);
  }
}

function displaySuccess() {
  console.log('\n╔════════════════════════════════════════╗');
  console.log('║                                        ║');
  console.log('║     ✅ Setup Complete!                 ║');
  console.log('║                                        ║');
  console.log('╚════════════════════════════════════════╝');
  console.log('\n📋 Next Steps:');
  console.log('   1. Ensure MongoDB is running (mongod)');
  console.log('   2. Start the server: npm run server');
  console.log('   3. Test the API: http://localhost:5000');
  console.log('\n💡 Optional: Edit .env to customize settings');
  console.log('   - Use MongoDB Atlas for cloud database');
  console.log('   - Change PORT if 5000 is busy');
  console.log('   - Update CLIENT_URL for your frontend\n');
}
